# Generated by Django 5.2.1 on 2025-06-27 18:52

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название места')),
                ('description_short', models.TextField(default='')),
                ('description_long', tinymce.models.HTMLField(default='')),
                ('long', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.location')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
