# Generated by Django 5.2.1 on 2025-06-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('description_short', models.TextField(blank=True, default='')),
                ('description_long', models.TextField(blank=True, default='')),
                ('long', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
            ],
        ),
    ]
