# Generated by Django 5.2.1 on 2025-06-19 17:10

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['place_id']},
        ),
        migrations.AddField(
            model_name='location',
            name='place_id',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='description_long',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='description_short',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Название места'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.location')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
