# Generated by Django 5.2.1 on 2025-06-02 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.location')),
            ],
        ),
    ]
