# Generated by Django 5.2.1 on 2025-06-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_location_options_location_place_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
