# Generated by Django 5.2.1 on 2025-06-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='place_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
