# Generated by Django 5.2.1 on 2025-06-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='place_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
