# Generated by Django 5.2.1 on 2025-06-13 11:22

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description_text',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
