# Generated by Django 5.2.1 on 2025-06-13 17:24

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_location_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='description_text',
        ),
        migrations.AlterField(
            model_name='location',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
