# Generated by Django 5.2.1 on 2025-06-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_remove_location_description_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Название места'),
        ),
    ]
