# Generated by Django 5.2.1 on 2025-06-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_location_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['place_id']},
        ),
    ]
